tinyalsa: include <sys/types.h> for ssize_t
ssize_t is defined in <sys/types.h>, see
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html

Add an include for it to avoid a compile error when building with musl:

../include/tinyalsa/plugin.h:184:5: error: expected specifier-qualifier-list before 'ssize_t'
  184 |     ssize_t (*read_event) (struct mixer_plugin *plugin,
      |     ^~~~~~~